// <auto-generated />
using ConfigManagementDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConfigManagementDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConfigManagementDemo.Models.ConfigurationItem", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Responsible");

                    b.Property<string>("Version");

                    b.HasKey("Name");

                    b.ToTable("ConfigurationItems");
                });

            modelBuilder.Entity("ConfigManagementDemo.Models.DependencyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseCiName");

                    b.Property<string>("DependencyCiName");

                    b.HasKey("Id");

                    b.HasIndex("BaseCiName");

                    b.HasIndex("DependencyCiName");

                    b.ToTable("DependencyItems");
                });

            modelBuilder.Entity("ConfigManagementDemo.Models.DependencyItem", b =>
                {
                    b.HasOne("ConfigManagementDemo.Models.ConfigurationItem", "BaseCi")
                        .WithMany("DependencyItems")
                        .HasForeignKey("BaseCiName");

                    b.HasOne("ConfigManagementDemo.Models.ConfigurationItem", "DependencyCi")
                        .WithMany("ItemsThatDepend")
                        .HasForeignKey("DependencyCiName");
                });
#pragma warning restore 612, 618
        }
    }
}
